site_name: SLE - Composition Benchmark
pages:
  - 'Home':
    - 'Index': 'index.md'
    - 'Initiatives': 'index/initiatives.md'
    - 'Workbenches': 'index/workbenches.md'
    - 'TODO': 'index/todo.md'
  - 'Benchmark':
      - 'Index': 'benchmark/index.md'
      - 'Vocabulary': 'benchmark/vocabulary.md'
      - 'Properties': 'benchmark/properties.md'
  - 'Challenges':
    - 'Index': 'challenges/index.md'
    - 'One Level Extension': 'challenges/one-level-extension/index.md'
    - 'Two Levels Extension': 'challenges/two-levels-extension/index.md'
    - 'Language Unification': 'challenges/languages-unification/index.md'
    - 'Independent Features Composition': 'challenges/independent-features-composition/index.md'
    - 'Self-Extension': 'challenges/language-self-extension/index.md'
    - 'Dead Features Detection': 'challenges/dead-features-detection/index.md'
  - 'Solutions': 'solutions/index.md'
  - 'Problems': 'problems/index.md'
  - 'About': 'about.md'
theme: flatly
